@startuml
Class ConstructorJuego{
-constructorJugador
-constructorTablero
-construtorVehiculo
+crearJuego(m,n, nick, vehiculo)
}
Class ConstructorTablero{
+crearConTamaño(m, n)
-unirCeldas(Esquinas)
}
Class ConstructorJugador{
+crearConNick(unNick)
}
Class ConstructorEsquinas{
+crearConTamaño(m,n)
}
Class ConstructorVehiculo{
+crearVehiculo(unVehiculo)
+crearVehiculoRandom()
}
ConstructorTablero *--up ConstructorJuego
ConstructorJugador *--up ConstructorJuego
ConstructorTablero *-down- ConstructorEsquinas
ConstructorVehiculo *--up ConstructorJuego
@enduml